---
scheming_version: 1
dataset_type: dataset
about: A reimplementation of the default CKAN dataset schema
about_url: http://github.com/ckan/ckanext-scheming

dataset_fields:

- field_name: title
  label: Title
  required: true
  preset: title
  form_placeholder: eg. A descriptive title

- field_name: name
  label: URL
  preset: dataset_slug
  form_placeholder: eg. my-dataset

- field_name: notes
  label: Description
  required: true
  form_snippet: markdown.html
  form_placeholder: 'eg. More info about data properties, provenance or usage restrictions.'

- field_name: maintainer_email
  label: Maintainer
  required: true
  form_placeholder: alias@idmod.org
  display_property: dc:contributor
  display_snippet: email.html
  display_email_name_field: maintainer_email

# Categorization

- field_name: purpose
  label: Purpose
  required: true
  preset: select
  choices:
  - value: data
    label: Raw Data
  - value: project
    label: Project Files
  - value: paper
    label: Published Paper

#- field_name: data_type
#  label: Data Type
#  preset: select
#  choices:
#  - value: raster
#    label: Raster
#  - value: shapes
#    label: Shapefile
#  - value: array
#    label: Array
#  - value: tabular
#    label: Tabular
#  - value: db
#    label: Database

- field_name: owner_org
  label: Research Group
  required: true
  preset: dataset_research_group

- field_name: disease
  label: Disease
  required: true
  preset: select
  choices_helper: get_diseases_choices

- field_name: tag_string
  label: Tags
  preset: tag_string_autocomplete
  form_placeholder: eg. economy, mental health, government

- field_name: quality
  label: Quality
  preset: select
  choices:
  - value: great
    label: Great
  - value: good
    label: Good
  - value: bad
    label: Bad

- field_name: quality_notes
  label: Quality Issues
  form_placeholder: 'e.g. inconsistent names, wrong coordinates, see temporal gaps, see attached resource.'

# Temporal

- field_name: ext_startdate
  label: Start Date
  required: true
  preset: date
  form_placeholder: eg. 01/01/2001

- field_name: ext_enddate
  label: End Date
  required: true
  preset: date
  form_placeholder: eg. 2018-12-31

- field_name: temporal_gaps
  label: Temporal Gaps
  form_placeholder: 'eg. missing years 2011 and 2016.'

# Spatial

- field_name: location
  label: Location
  required: true
  preset: location_autocomplete

- field_name: spatial_gaps
  label: Spatial Gaps
  form_placeholder: 'eg. missing area north from N12.'

- field_name: spatial_resolution
  label: Spatial Resolution
  form_placeholder: 'eg. 0.25 degrees, 30'', 2.5'', 1km, 750m'

# Provenance

- field_name: publisher
  label: Publisher
  required: true
  preset: publisher_autocomplete

- field_name: url
  label: Origin URL
  form_placeholder: http://example.com/dataset.json
  display_property: foaf:homepage
  display_snippet: link.html

- field_name: acquisition_date
  label: Acquisition Date
  required: true
  preset: date
  form_placeholder: eg. 2018-12-31

- field_name: version
  label: Version
  required: true
  validators: ignore_missing unicode package_version_validator
  form_placeholder: '1.0'

# Access

#- field_name: private
#  label: Visibility
#  required: true
#  preset: select
#  value: False
#  choices:
#  - value: True
#    label: Only Research Group users can see

- field_name: request_access
  label: Restricted
  preset: multiple_checkbox
  choices:
  - value: maintainer
    label: Must request access from maintainer

- field_name: license_id
  label: License
  form_snippet: license_field.html
  help_text: License definitions and additional information can be found at http://opendefinition.org/


resource_fields:

- field_name: url
  label: URL
  preset: resource_url_upload

- field_name: name
  label: Name
  required: true
  form_placeholder: eg. weather files

- field_name: purpose
  label: Purpose
  required: true
  preset: select
  choices:
  - value: data
    label: Data
  - value: code
    label: Code
  - value: doc
    label: Document
  - value: paper
    label: Paper

- field_name: description
  label: Description
  form_snippet: markdown.html
  form_placeholder: Some useful notes about the data

- field_name: format
  label: Format
  preset: resource_format_autocomplete
