---
scheming_version: 1
dataset_type: dataset
about: A reimplementation of the default CKAN dataset schema
about_url: http://github.com/ckan/ckanext-scheming

dataset_fields:

- field_name: title
  label: Title
  required: true
  preset: title
  form_placeholder: eg. A descriptive title

- field_name: name
  label: URL
  preset: dataset_slug
  form_placeholder: eg. my-dataset

- field_name: notes
  label: Description
  required: true
  form_snippet: markdown.html
  form_placeholder: 'eg. More info about data properties, provenance or usage recommendations.'

- field_name: maintainer_email
  label: Maintainer
  required: true
  preset: maintainer_autocomplete
  display_property: dc:creator
  display_snippet: email.html
  display_email_name_field: maintainer
  help_text: Enter or pick a username, enter an email or copy-paste a contact from an email (e.g. First Last <alias@server.org>).

# Categorization

- field_name: purpose
  label: Purpose
  required: true
  preset: select
  choices:
  - value: data
    label: Raw Data
  - value: project
    label: Project Files
  - value: paper
    label: Published Paper
  help_text: "Raw Data - used as input to project pipeline || Project Files: tracks research workflow || Published Paper: all data for reproducing the paper."


#- field_name: data_type
#  label: Data Type
#  preset: select
#  choices:
#  - value: raster
#    label: Raster
#  - value: shapes
#    label: Shapefile
#  - value: array
#    label: Array
#  - value: tabular
#    label: Tabular
#  - value: db
#    label: Database

- field_name: owner_org
  label: Research Group
  required: true
  preset: dataset_research_group
  help_text: "Public - anyone can see || Private - visible only to research group members."

- field_name: disease
  label: Disease
  required: true
  preset: multiple_select
  choices_helper: get_diseases_choices

- field_name: tag_string
  label: Tags
  preset: tag_string_autocomplete
  form_placeholder: eg. economy, mental health, government
  help_text: Start typing. Pick from the list or enter a new value. Press Tab or Enter to enter a tag.

- field_name: quality
  label: Quality Rating
  preset: select
  choices:
  - value: great
    label: Great
  - value: good
    label: Good
  - value: bad
    label: Bad
  help_text: "Great - no major issues. || Good - some issue but still usable. || Bad - many issues, difficult to use."

- field_name: quality_notes
  label: Quality Issues
  form_placeholder: 'e.g. inconsistent names, wrong coordinates, see temporal gaps, see attached resource.'
  help_text: Enumerate most impactful quality issues. This should help others decide whether to use the dataset.

# Temporal

- field_name: ext_startdate
  label: Start Date
  required: true
  validators: not_empty reasonable_range_date temporal_range
  preset: date
  help_text: Temporal range start date, e.g. 01/01/2001.

- field_name: ext_enddate
  label: End Date
  required: true
  validators: not_empty reasonable_range_date temporal_range
  preset: date
  help_text: Temporal range start date, e.g. 2018-12-31.

- field_name: temporal_gaps
  label: Temporal Gaps
  form_placeholder: 'e.g. missing years 2011 and 2016.'
  help_text: If applicable, describe which portion of the temporal range, defined by start/end date, is not covered by this dataset.

# Spatial

- field_name: location
  label: Location
  required: true
  preset: location_autocomplete
  help_text: The name of the location that best describes spatial scope of the dataset. Choose from the list or enter a new value.

- field_name: spatial
  label: Extent
  validators: ignore_missing remove_whitespace set_spatial_to_location_geometry
  form_placeholder: 'e.g. { "type": "Polygon", "coordinates": [ [ [50.8, -34.2],[50.8, 36.7], [-19.9, 36.7], [-19.9, -34.2], [50.8, -34.2] ] ] }'
  help_text: Location GeoJSON (geometry attribute), set automatically if name path is picked from the list, e.g. Africa:Zambia. Enables spatial search.

- field_name: spatial_mode
  label: Extent Mode
  preset: multiple_checkbox
  choices:
  - value: manual
    label: Location extent is set manually.
  help_text: Check to enter location GeoJSON geometry manually.

- field_name: spatial_gaps
  label: Spatial Gaps
  form_placeholder: 'e.g. missing area north from N12.'
  help_text: If applicable, describe which portion of the chosen location is not covered by this dataset.

- field_name: spatial_resolution
  label: Spatial Resolution
  form_placeholder: 'e.g. 0.25 degrees, 30'', 2.5'', 1km, 750m'
  help_text: The dataset spatial resolution.

# Provenance

- field_name: publisher
  label: Publisher
  required: true
  preset: publisher_autocomplete
  help_text: The name of the organization or entity which created and published the dataset. Choose from the list or enter a new value.

- field_name: url
  label: Publisher URL
  form_placeholder: http://example.com/dataset.json
  display_property: foaf:homepage
  display_snippet: link.html
  help_text: A link to a publisher's website. Preferably to a page which describes the dataset and how to obtain it.

- field_name: acquisition_date
  label: Acquisition Date
  required: true
  validators: not_empty reasonable_acquisition_date
  preset: date
  form_placeholder: e.g. 2018-12-31
  help_text: The date when the dataset was obtained from the publisher.

- field_name: version
  label: Version
  validators: ignore_missing unicode package_version_validator
  form_placeholder: '1.0'
  help_text: The version information if applicable. If known, enter the exact version as used by Publisher.

# Access

#- field_name: private
#  label: Visibility
#  required: true
#  preset: select
#  value: False
#  choices:
#  - value: True
#    label: Only Research Group users can see

- field_name: request_access
  label: Restricted
  preset: multiple_checkbox
  choices:
  - value: maintainer
    label: Must request access from maintainer
  help_text: Checked to indicate that access to the dataset must be explicitly approved by the maintainer.

- field_name: terms_of_use
  label: Terms of Use
  required: false
  form_snippet: markdown.html
  form_placeholder: e.g. Publicly available, please cite when used for model development.
  help_text: The terms of use details, disclaimers and other usage restrictions.

- field_name: license_id
  label: License Type
  required: true
  form_snippet: license_field.html
  help_text: License definitions and additional information can be found at http://opendefinition.org/



resource_fields:

- field_name: url
  label: URL
  preset: resource_url_upload

- field_name: name
  label: Name
  required: true
  #preset: resource_name_handle_enter_key
  form_placeholder: e.g. weather files

- field_name: purpose
  label: Purpose
  required: true
  preset: select
  choices:
  - value: data
    label: Data
  - value: code
    label: Code
  - value: doc
    label: Document
  - value: paper
    label: Paper
  - value: provenance
    label: Provenance
  - value: other
    label: Other
  help_text: Select based on the main purpose of the resource.


- field_name: description
  label: Description
  form_snippet: markdown.html
  form_placeholder: Some useful notes about the data

- field_name: format
  label: Format
  preset: resource_format_autocomplete
  help_text: The resource file format, if applicable. If the resource has multiple formats, choose the most representative one (or split the resource into multiple).
