# encoding: utf-8

import argparse
import os
import socket
import sys
import yaml

from string import punctuation
from ckanapi import RemoteCKAN

import helpers as hlp

# Before this script can run there has to be at least one sysadmin user whose API key is used for loading data.
#
# paster user add dlukacevic email=dlukacevic@idmod.org fullname="Dejan Lukacevic" -c /etc/ckan/production.ini
# paster sysadmin add dlukacevic -c /etc/ckan/production.ini


def main(args):
    u"""
    Populate IDM CKAN instance with initial data. Supported scenarios:
    1. From a docker host (computer name used for both API and images url.)
    2. From within CKAN container (computer name for API URL and env. CKAN_SITE_URL for images)
    3. Against a remote CKAN server (CKAN URL must be given as an argument, to be used for both API and images url)
    """

    # Construct CKAN url and initiate API object.
    host_url = args.ckan_url or u'http://localhost:5000'
    act = RemoteCKAN(host_url, apikey=args.api_key).action

    # Fail safe, only run if DB is empty or unless "force" flag is used.
    if not args.force:
        try:
            hlp.fail_safe_check(args.force, act.user_list, u'users', max_count=2)
            hlp.fail_safe_check(args.force, act.organization_list, u'research groups')
            hlp.fail_safe_check(args.force, act.group_list, u'topics')

        except ImportError as e:
            print e.message
            sys.exit(1)

        # Load data from a file and separate research groups and topics.
    items = hlp.load_yaml(args.file)
    rgroups = items[u'research_groups'] if items and items.get(u'research_groups') else {}
    topics = items[u'topics'] if items and items.get(u'topics') else {}
    tags = items[u'tags'] if items and items.get(u'tags') else {}

    # Create users, research groups and topics.
    create_research_groups_and_users(act, rgroups)
    create_topics(act, topics)
    create_tag_vocabularies(act, tags)


def fail_safe_check(act, func, label, max_count=0):
    message_end = u'Data bootstraping works only on an empty database or if "--force" flag is used.'
    cnt = len(func(all_fields=False))
    if cnt > max_count:
        raise ImportError(u'Fail-safe: Found {} existing {}. {} Use "--force" flag to override.'.format(cnt, label, message_end))


def get_image_url_prefix():
    """Determines image URL prefix."""
    if args.ckan_url:
        host_url = args.ckan_url
    elif u'CKAN_SITE_URL' in os.environ:
        host_url = os.environ[u'CKAN_SITE_URL']
    else:
        host_url = u'http://{}:5000'.format(socket.gethostname())

    return host_url


def create_research_groups_and_users(act, rgroups):
    u"""Iterate over research groups (RG), create each RG add listed member users."""
    for name, info in rgroups.items():
        members = []

        # Create the admin user
        if info and info.get(u'admin'):
            admin = create_single_user(act, info[u'admin'], members)

        # Create listed member users
        if info and info.get(u'members'):
            members_raw = [u.strip() for u in info[u'members'].split(u';')]
            members_raw = list(set(members_raw))
            for member_raw in members_raw:
                create_single_user(act, member_raw, members)

        # Create the research group adding listed users as members.
        title = info[u'title'] if info and info.get(u'title') else name
        description = info[u'description'] if info and info.get(u'description') else u''
        api_create_research_group(act, name, title, description, admin, members)


def create_single_user(act, user_raw, all_members):
    u"""Create a user calling API and if successful return user name."""
    username, full_name, email = parse_user(user_raw)
    member = api_create_user(act, username, full_name, email, args.password)
    if member:
        assert member == username
        all_members.append(member)

    return username


def parse_user(outlook_paste):
    u"""Parse user info from the user string (generated by copy-pasting from Outlook)."""
    full_name, email_raw = outlook_paste.split(u' <')
    email = email_raw.strip(punctuation)
    username = email.split(u'@')[0].lower()

    return username, full_name, email


def api_create_user(act, username, full_name, email, password):
    u"""Create a user by calling API via the common method."""
    args_dict = {u'name': username, u'email': email, u'fullname': full_name, u'password': password}

    success_msg = u'Created a new user {}'.format(username)
    errors_to_skip = [
        {
            u'error':u'name is not available',
            u'message':u'User already exists: {}'.format(username)
        }
    ]

    if not args.dryrun:
        new_user = hlp.call_api(act.user_create, args_dict, success_msg, errors_to_skip)
    else:
        new_user = None

    name = new_user[u'name'] if new_user and new_user.get(u'name') else None

    return name


def api_create_research_group(act, name, title, description, admin, members):
    u"""Create a research group by calling API via the common method."""
    host_url = get_image_url_prefix()
    image_url = u'{}/images/rgroup-{}.png'.format(host_url, name)

    # Research Group (organization) roles: member - see all datasets, editor - edit datasets, admin - manage info
    users = [{u'name': username, u'capacity': u'editor'} for username in members if username != admin]
    users.append({u'name': admin, u'capacity': u'admin'})

    args_dict = {u'name': name, u'title': title, u'description': description, u'image_url': image_url, u'users': users}

    success_msg = u'Created a new research group {}'.format(title)
    errors_to_skip = [
        {
            u'error':u'name already exists',
            u'message':u'Research Group already exists: {}'.format(title)
        }
    ]

    if not args.dryrun:
        hlp.call_api(act.organization_create, args_dict, success_msg, errors_to_skip)


def create_topics(act, topics):
    u"""Iterate over topics and create them."""
    for name, info in topics.items():
        title = info[u'title'] if info and info.get(u'title') else name
        description = info[u'description'] if info and info.get(u'description') else u''
        admin = info[u'admin']
        api_create_topic(act, name, title, description, admin)


def create_tag_vocabularies(act, tags):
    u"""Iterate over tag vocabularies and create them with tags."""
    for vocabulary_id, tag_list in tags.items():
        api_create_tag_vocabulary(act, vocabulary_id, tag_list)


def api_create_tag_vocabulary(act, vocabulary_id, tag_list):
    # , u'vocabulary_id': vocabulary_id
    tags_dicts = [{u'name': t} for t in tag_list]
    args_dict = {u'name': vocabulary_id, u'tags': tags_dicts}

    success_msg = u'Created a new tag vocabulary {}'.format(vocabulary_id)
    errors_to_skip = [
        {
            u'error': u'That vocabulary name is already in use',
            u'message': u'Vocabulary already exists: {}'.format(vocabulary_id)
        }
    ]

    if not args.dryrun:
        hlp.call_api(act.vocabulary_create, args_dict, success_msg, errors_to_skip)


def api_create_topic(act, name, title, description, admin):
    u"""Create a topic by calling API via the common method."""
    host_url = get_image_url_prefix()
    image_url = u'{}/images/topic-{}.png'.format(host_url, name)
    # Make all research group admins as topic admins.
    admin_users = [{u'name': admin, u'capacity': u'admin'}]

    # Topics (group) roles: admin - manage info, member - add data to the topic (all can see the groups and datasets)
    # TODO: Ensure all users can add datasets to topics. determine which users will be topic admins.
    args_dict = {u'name': name, u'title': title, u'description': description, u'image_url': image_url, u'users': admin_users}

    success_msg = u'Created a new topic {}'.format(title)
    errors_to_skip = [
        {
            u'error':u'name already exists',
            u'message':u'Topic already exists: {}'.format(title)
        }
    ]

    if not args.dryrun:
        hlp.call_api(act.group_create, args_dict, success_msg, errors_to_skip)



def parse_args():
    example = ur"python bootstrap.py 2f83d65d-e5e9-4e22-9c52-baaf898c2022"
    parser = argparse.ArgumentParser(example)
    parser.add_argument(u'api_key')
    parser.add_argument(u'-f', u'--file', default=u'metadata.yaml')
    parser.add_argument(u'-p', u'--password', default=u'Password123')
    parser.add_argument(u'--url', dest='ckan_url', default=None)
    parser.add_argument(u'--dryrun', action=u'store_true')
    parser.add_argument(u'--force', action=u'store_true')
    return parser.parse_args()


if __name__ == u"__main__":
    args = parse_args()
    main(args)


